DUEL_TIMEOUT = 180
MESSAGE_BEGIN = ["> ", "、"]
TIME_NORMAL = 60
TIME_SPEED = 15
END_DUEL = "> end"

PACE_NORMAL = "normal"
PACE_SPEED = "speed"

INPUT_ROMAJI = "romaji"
INPUT_KANA = "かな"
INPUT_KANJI = "漢字"
